server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: microcuenta
            uri: lb://microcuenta
            predicates:
              - Path=/cuenta/**
          - id: microestacion
            uri: lb://microestacion
            predicates:
              - Path=/estacion/**
          - id: microfacturacion
            uri: lb://microfacturacion
            predicates:
              - Path=/facturacion/**
          - id: micromantenimiento
            uri: lb://micromantenimiento
            predicates:
              - Path=/mantenimiento/**
          - id: micromonopatin
            uri: lb://micromonopatin
            predicates:
              - Path=/monopatin/**
          - id: microusuario
            uri: lb://microusuario
            predicates:
              - Path=/usuario/**
          - id: microviaje
            uri: lb://microviaje
            predicates:
              - Path=/viaje/**
          - id: microadministrador
            uri: lb://microadministrador
            predicates:
             - Path=/administrador/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

