spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8081
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true
    username: root
    password: # Asegúrate de agregar tu contraseña aquí si es necesaria
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
